-- Create campaigns table for bulk WhatsApp messaging
-- Run this in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS campaigns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT REFERENCES business_profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  goal TEXT,
  message TEXT NOT NULL,
  tone TEXT DEFAULT 'auto',
  audience_type TEXT DEFAULT 'all',
  audience_filter JSONB,
  schedule_type TEXT DEFAULT 'now',
  scheduled_at TIMESTAMPTZ,
  status TEXT DEFAULT 'draft',
  messages_sent INT DEFAULT 0,
  responses INT DEFAULT 0,
  response_rate REAL DEFAULT 0,
  estimated_reach INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add campaign_id column to messages table if not exists
ALTER TABLE messages ADD COLUMN IF NOT EXISTS campaign_id BIGINT REFERENCES campaigns(id) ON DELETE SET NULL;

-- Index for faster lookups
CREATE INDEX IF NOT EXISTS idx_campaigns_business_id ON campaigns(business_id);
CREATE INDEX IF NOT EXISTS idx_campaigns_status ON campaigns(status);
CREATE INDEX IF NOT EXISTS idx_messages_campaign_id ON messages(campaign_id);
